// Hand-curated syllable breakdowns for all seed words.
// English words use standard English syllabification.
// Te reo Māori words use Māori phonology (CV pattern, digraphs ng/wh).

export const syllableMap: Record<string, string[]> = {
  // ── A ──────────────────────────────────────────────────────────────
  a: ["a"],
  about: ["a", "bout"],
  accommodate: ["ac", "com", "mo", "date"],
  accompany: ["ac", "com", "pa", "ny"],
  according: ["ac", "cord", "ing"],
  achieve: ["a", "chieve"],
  acknowledgement: ["ac", "knowl", "edge", "ment"],
  action: ["ac", "tion"],
  advertise: ["ad", "ver", "tise"],
  advise: ["ad", "vise"],
  after: ["af", "ter"],
  again: ["a", "gain"],
  aggressive: ["ag", "gres", "sive"],
  agreement: ["a", "gree", "ment"],
  albatross: ["al", "ba", "tross"],
  all: ["all"],
  allowed: ["al", "lowed"],
  aloud: ["a", "loud"],
  also: ["al", "so"],
  although: ["al", "though"],
  always: ["al", "ways"],
  am: ["am"],
  an: ["an"],
  and: ["and"],
  animals: ["an", "i", "mals"],
  another: ["an", "oth", "er"],
  any: ["an", "y"],
  aotearoa: ["a", "o", "te", "a", "ro", "a"],
  apologise: ["a", "pol", "o", "gise"],
  apparently: ["ap", "par", "ent", "ly"],
  appreciate: ["ap", "pre", "ci", "ate"],
  are: ["are"],
  armour: ["ar", "mour"],
  aroha: ["a", "ro", "ha"],
  around: ["a", "round"],
  as: ["as"],
  asked: ["asked"],
  at: ["at"],
  attention: ["at", "ten", "tion"],
  atua: ["a", "tu", "a"],
  Auckland: ["Auck", "land"],
  August: ["Au", "gust"],
  autumn: ["au", "tumn"],
  away: ["a", "way"],
  awhile: ["a", "while"],
  awkward: ["awk", "ward"],

  // ── B ──────────────────────────────────────────────────────────────
  baby: ["ba", "by"],
  back: ["back"],
  bad: ["bad"],
  ball: ["ball"],
  bargain: ["bar", "gain"],
  be: ["be"],
  beautiful: ["beau", "ti", "ful"],
  because: ["be", "cause"],
  bed: ["bed"],
  been: ["been"],
  before: ["be", "fore"],
  behaviour: ["be", "hav", "iour"],
  being: ["be", "ing"],
  believe: ["be", "lieve"],
  best: ["best"],
  better: ["bet", "ter"],
  big: ["big"],
  bit: ["bit"],
  black: ["black"],
  boat: ["boat"],
  book: ["book"],
  bought: ["bought"],
  boy: ["boy"],
  breakfast: ["break", "fast"],
  breathe: ["breathe"],
  brother: ["broth", "er"],
  bruise: ["bruise"],
  bus: ["bus"],
  bush: ["bush"],
  but: ["but"],
  by: ["by"],

  // ── C ──────────────────────────────────────────────────────────────
  calendar: ["cal", "en", "dar"],
  called: ["called"],
  came: ["came"],
  camp: ["camp"],
  can: ["can"],
  cancelled: ["can", "celled"],
  cancelling: ["can", "cel", "ling"],
  car: ["car"],
  careful: ["care", "ful"],
  cat: ["cat"],
  catalogue: ["cat", "a", "logue"],
  category: ["cat", "e", "gor", "y"],
  caught: ["caught"],
  celebration: ["cel", "e", "bra", "tion"],
  cemetery: ["cem", "e", "ter", "y"],
  centre: ["cen", "tre"],
  cheerful: ["cheer", "ful"],
  cheque: ["cheque"],
  children: ["chil", "dren"],
  chocolate: ["choc", "o", "late"],
  city: ["cit", "y"],
  clothes: ["clothes"],
  collection: ["col", "lec", "tion"],
  colour: ["col", "our"],
  colourful: ["col", "our", "ful"],
  come: ["come"],
  coming: ["com", "ing"],
  committee: ["com", "mit", "tee"],
  communicate: ["com", "mu", "ni", "cate"],
  community: ["com", "mu", "ni", "ty"],
  competition: ["com", "pe", "ti", "tion"],
  compromise: ["com", "pro", "mise"],
  conscience: ["con", "science"],
  conscious: ["con", "scious"],
  consequence: ["con", "se", "quence"],
  controversy: ["con", "tro", "ver", "sy"],
  convenient: ["con", "ven", "ient"],
  cool: ["cool"],
  correspond: ["cor", "re", "spond"],
  could: ["could"],
  "couldn't": ["could", "n't"],
  counsellor: ["coun", "sel", "lor"],
  creature: ["crea", "ture"],
  criticise: ["crit", "i", "cise"],
  culture: ["cul", "ture"],
  curiosity: ["cu", "ri", "os", "i", "ty"],

  // ── D ──────────────────────────────────────────────────────────────
  dad: ["dad"],
  dark: ["dark"],
  day: ["day"],
  dead: ["dead"],
  decided: ["de", "cid", "ed"],
  defence: ["de", "fence"],
  definite: ["def", "i", "nite"],
  describe: ["de", "scribe"],
  desperate: ["des", "per", "ate"],
  destroy: ["de", "stroy"],
  determined: ["de", "ter", "mined"],
  develop: ["de", "vel", "op"],
  dialogue: ["di", "a", "logue"],
  diary: ["di", "a", "ry"],
  dictionary: ["dic", "tion", "ar", "y"],
  did: ["did"],
  "didn't": ["did", "n't"],
  died: ["died"],
  different: ["dif", "fer", "ent"],
  direction: ["di", "rec", "tion"],
  disappear: ["dis", "ap", "pear"],
  disappoint: ["dis", "ap", "point"],
  disease: ["dis", "ease"],
  distance: ["dis", "tance"],
  divide: ["di", "vide"],
  do: ["do"],
  dog: ["dog"],
  doing: ["do", "ing"],
  dollars: ["dol", "lars"],
  dolphin: ["dol", "phin"],
  "don't": ["don't"],
  door: ["door"],
  down: ["down"],

  // ── E ──────────────────────────────────────────────────────────────
  each: ["each"],
  earthquake: ["earth", "quake"],
  eat: ["eat"],
  eight: ["eight"],
  embarrass: ["em", "bar", "rass"],
  emphasise: ["em", "pha", "sise"],
  end: ["end"],
  endeavour: ["en", "deav", "our"],
  energy: ["en", "er", "gy"],
  engine: ["en", "gine"],
  environment: ["en", "vi", "ron", "ment"],
  equation: ["e", "qua", "tion"],
  equipped: ["e", "quipped"],
  escape: ["es", "cape"],
  especially: ["e", "spe", "cial", "ly"],
  even: ["e", "ven"],
  ever: ["ev", "er"],
  every: ["ev", "er", "y"],
  everybody: ["ev", "ery", "bod", "y"],
  everyone: ["ev", "ery", "one"],
  everything: ["ev", "ery", "thing"],
  excellent: ["ex", "cel", "lent"],
  excitement: ["ex", "cite", "ment"],
  exercise: ["ex", "er", "cise"],
  exaggerate: ["ex", "ag", "ger", "ate"],
  existence: ["ex", "ist", "ence"],
  experiment: ["ex", "per", "i", "ment"],
  explanation: ["ex", "pla", "na", "tion"],
  eyes: ["eyes"],

  // ── F ──────────────────────────────────────────────────────────────
  face: ["face"],
  family: ["fam", "i", "ly"],
  familiar: ["fa", "mil", "i", "ar"],
  fantail: ["fan", "tail"],
  fast: ["fast"],
  father: ["fa", "ther"],
  favourite: ["fa", "vour", "ite"],
  February: ["Feb", "ru", "ar", "y"],
  fell: ["fell"],
  felt: ["felt"],
  fern: ["fern"],
  few: ["few"],
  fibre: ["fi", "bre"],
  film: ["film"],
  finally: ["fi", "nal", "ly"],
  find: ["find"],
  finished: ["fin", "ished"],
  fiord: ["fiord"],
  first: ["first"],
  five: ["five"],
  flavour: ["fla", "vour"],
  flax: ["flax"],
  food: ["food"],
  for: ["for"],
  foreign: ["for", "eign"],
  forest: ["for", "est"],
  found: ["found"],
  four: ["four"],
  fraction: ["frac", "tion"],
  frequently: ["fre", "quent", "ly"],
  friend: ["friend"],
  friends: ["friends"],
  from: ["from"],
  front: ["front"],
  fruit: ["fruit"],
  fun: ["fun"],

  // ── G ──────────────────────────────────────────────────────────────
  game: ["game"],
  gave: ["gave"],
  gently: ["gen", "tly"],
  get: ["get"],
  getting: ["get", "ting"],
  geyser: ["gey", "ser"],
  girl: ["girl"],
  glacier: ["gla", "cier"],
  glamour: ["glam", "our"],
  go: ["go"],
  going: ["go", "ing"],
  gone: ["gone"],
  good: ["good"],
  got: ["got"],
  government: ["gov", "ern", "ment"],
  grabbed: ["grabbed"],
  great: ["great"],
  ground: ["ground"],
  guarantee: ["guar", "an", "tee"],
  guard: ["guard"],

  // ── H ──────────────────────────────────────────────────────────────
  habitat: ["hab", "i", "tat"],
  had: ["had"],
  haere: ["ha", "e", "re"],
  haka: ["ha", "ka"],
  half: ["half"],
  hand: ["hand"],
  hangi: ["ha", "ngi"],
  happened: ["hap", "pened"],
  happy: ["hap", "py"],
  harakeke: ["ha", "ra", "ke", "ke"],
  harbour: ["har", "bour"],
  has: ["has"],
  have: ["have"],
  he: ["he"],
  head: ["head"],
  hear: ["hear"],
  heard: ["heard"],
  height: ["height"],
  help: ["help"],
  her: ["her"],
  here: ["here"],
  him: ["him"],
  his: ["his"],
  hit: ["hit"],
  hole: ["hole"],
  home: ["home"],
  honour: ["hon", "our"],
  hopeful: ["hope", "ful"],
  hoping: ["hop", "ing"],
  hot: ["hot"],
  hour: ["hour"],
  house: ["house"],
  how: ["how"],
  hui: ["hu", "i"],
  humour: ["hu", "mour"],
  hungry: ["hun", "gry"],

  // ── I ──────────────────────────────────────────────────────────────
  I: ["I"],
  if: ["if"],
  imagine: ["i", "mag", "ine"],
  immediately: ["im", "me", "di", "ate", "ly"],
  important: ["im", "por", "tant"],
  improvise: ["im", "pro", "vise"],
  in: ["in"],
  independent: ["in", "de", "pend", "ent"],
  inside: ["in", "side"],
  interesting: ["in", "ter", "est", "ing"],
  interrupt: ["in", "ter", "rupt"],
  into: ["in", "to"],
  is: ["is"],
  island: ["is", "land"],
  it: ["it"],
  its: ["its"],
  iwi: ["i", "wi"],

  // ── J ──────────────────────────────────────────────────────────────
  January: ["Jan", "u", "ar", "y"],
  jewellery: ["jew", "el", "ry"],
  judge: ["judge"],
  jump: ["jump"],
  jumped: ["jumped"],
  just: ["just"],

  // ── K ──────────────────────────────────────────────────────────────
  kai: ["kai"],
  kaiako: ["kai", "a", "ko"],
  kaitiaki: ["kai", "ti", "a", "ki"],
  karakia: ["ka", "ra", "ki", "a"],
  karanga: ["ka", "ra", "nga"],
  kaumatua: ["kau", "ma", "tu", "a"],
  kaupapa: ["kau", "pa", "pa"],
  kauri: ["kau", "ri"],
  kawakawa: ["ka", "wa", "ka", "wa"],
  kereru: ["ke", "re", "ru"],
  "kia ora": ["ki", "a", "o", "ra"],
  kindly: ["kind", "ly"],
  kiwi: ["ki", "wi"],
  knew: ["knew"],
  know: ["know"],
  knowledge: ["knowl", "edge"],
  koha: ["ko", "ha"],
  korero: ["ko", "re", "ro"],
  kotahitanga: ["ko", "ta", "hi", "ta", "nga"],
  kowhai: ["ko", "whai"],
  kumara: ["ku", "ma", "ra"],

  // ── L ──────────────────────────────────────────────────────────────
  labelled: ["la", "belled"],
  labour: ["la", "bour"],
  language: ["lan", "guage"],
  last: ["last"],
  later: ["la", "ter"],
  left: ["left"],
  leisure: ["lei", "sure"],
  let: ["let"],
  licence: ["li", "cence"],
  life: ["life"],
  light: ["light"],
  lightning: ["light", "ning"],
  like: ["like"],
  liquid: ["liq", "uid"],
  litre: ["li", "tre"],
  little: ["lit", "tle"],
  live: ["live"],
  long: ["long"],
  look: ["look"],
  looked: ["looked"],
  lot: ["lot"],
  loudly: ["loud", "ly"],
  luckily: ["luck", "i", "ly"],
  lunch: ["lunch"],
  lustre: ["lus", "tre"],

  // ── M ──────────────────────────────────────────────────────────────
  made: ["made"],
  mahi: ["ma", "hi"],
  make: ["make"],
  man: ["man"],
  mana: ["ma", "na"],
  manaakitanga: ["ma", "naa", "ki", "ta", "nga"],
  many: ["man", "y"],
  marae: ["ma", "ra", "e"],
  marvellous: ["mar", "vel", "lous"],
  material: ["ma", "te", "ri", "al"],
  maunga: ["mau", "nga"],
  me: ["me"],
  measurement: ["meas", "ure", "ment"],
  men: ["men"],
  metre: ["me", "tre"],
  migration: ["mi", "gra", "tion"],
  might: ["might"],
  mihi: ["mi", "hi"],
  minutes: ["min", "utes"],
  mischievous: ["mis", "chie", "vous"],
  moana: ["mo", "a", "na"],
  modelled: ["mod", "elled"],
  moment: ["mo", "ment"],
  money: ["mon", "ey"],
  more: ["more"],
  morning: ["morn", "ing"],
  mother: ["moth", "er"],
  mountain: ["moun", "tain"],
  movement: ["move", "ment"],
  Mrs: ["Mrs"],
  much: ["much"],
  multiply: ["mul", "ti", "ply"],
  mum: ["mum"],
  must: ["must"],
  my: ["my"],
  myself: ["my", "self"],

  // ── N ──────────────────────────────────────────────────────────────
  name: ["name"],
  nearly: ["near", "ly"],
  necessary: ["nec", "es", "sar", "y"],
  neighbour: ["neigh", "bour"],
  never: ["nev", "er"],
  new: ["new"],
  next: ["next"],
  nice: ["nice"],
  night: ["night"],
  no: ["no"],
  not: ["not"],
  noticed: ["no", "ticed"],
  now: ["now"],
  nuisance: ["nui", "sance"],

  // ── O ──────────────────────────────────────────────────────────────
  occasion: ["oc", "ca", "sion"],
  of: ["of"],
  off: ["off"],
  old: ["old"],
  on: ["on"],
  once: ["once"],
  one: ["one"],
  only: ["on", "ly"],
  opened: ["o", "pened"],
  opportunity: ["op", "por", "tu", "ni", "ty"],
  or: ["or"],
  ordinary: ["or", "di", "nar", "y"],
  organise: ["or", "gan", "ise"],
  other: ["oth", "er"],
  our: ["our"],
  out: ["out"],
  outside: ["out", "side"],
  over: ["o", "ver"],

  // ── P ──────────────────────────────────────────────────────────────
  Pacific: ["Pa", "cif", "ic"],
  papatuanuku: ["pa", "pa", "tu", "a", "nu", "ku"],
  parents: ["par", "ents"],
  parliament: ["par", "lia", "ment"],
  patu: ["pa", "tu"],
  paua: ["pa", "u", "a"],
  peace: ["peace"],
  penguin: ["pen", "guin"],
  peninsula: ["pen", "in", "su", "la"],
  people: ["peo", "ple"],
  pepeha: ["pe", "pe", "ha"],
  perhaps: ["per", "haps"],
  persuade: ["per", "suade"],
  physical: ["phys", "i", "cal"],
  picked: ["picked"],
  piece: ["piece"],
  pipi: ["pi", "pi"],
  place: ["place"],
  planet: ["plan", "et"],
  play: ["play"],
  playing: ["play", "ing"],
  pohutukawa: ["po", "hu", "tu", "ka", "wa"],
  poi: ["poi"],
  population: ["pop", "u", "la", "tion"],
  possum: ["pos", "sum"],
  pounamu: ["po", "u", "na", "mu"],
  practise: ["prac", "tise"],
  prejudice: ["prej", "u", "dice"],
  presents: ["pres", "ents"],
  privilege: ["priv", "i", "lege"],
  profession: ["pro", "fes", "sion"],
  programme: ["pro", "gramme"],
  pronunciation: ["pro", "nun", "ci", "a", "tion"],
  puku: ["pu", "ku"],
  purpose: ["pur", "pose"],
  put: ["put"],

  // ── Q ──────────────────────────────────────────────────────────────
  question: ["ques", "tion"],
  quickly: ["quick", "ly"],
  quietly: ["qui", "et", "ly"],

  // ── R ──────────────────────────────────────────────────────────────
  ran: ["ran"],
  rangatira: ["ra", "nga", "ti", "ra"],
  rangatiratanga: ["ra", "nga", "ti", "ra", "ta", "nga"],
  rata: ["ra", "ta"],
  read: ["read"],
  ready: ["read", "y"],
  realise: ["re", "al", "ise"],
  really: ["real", "ly"],
  rebuild: ["re", "build"],
  receive: ["re", "ceive"],
  recognise: ["rec", "og", "nise"],
  recommend: ["rec", "om", "mend"],
  rectangle: ["rec", "tan", "gle"],
  relevant: ["rel", "e", "vant"],
  remember: ["re", "mem", "ber"],
  reo: ["re", "o"],
  replay: ["re", "play"],
  reread: ["re", "read"],
  restaurant: ["res", "tau", "rant"],
  retell: ["re", "tell"],
  return: ["re", "turn"],
  revise: ["re", "vise"],
  rewrite: ["re", "write"],
  rhyme: ["rhyme"],
  rhythm: ["rhy", "thm"],
  ride: ["ride"],
  right: ["right"],
  rimu: ["ri", "mu"],
  road: ["road"],
  room: ["room"],
  round: ["round"],
  rumour: ["ru", "mour"],
  run: ["run"],

  // ── S ──────────────────────────────────────────────────────────────
  sacrifice: ["sac", "ri", "fice"],
  safety: ["safe", "ty"],
  said: ["said"],
  sailor: ["sail", "or"],
  sandfly: ["sand", "fly"],
  Saturday: ["Sat", "ur", "day"],
  savour: ["sa", "vour"],
  saw: ["saw"],
  say: ["say"],
  school: ["school"],
  scissors: ["scis", "sors"],
  sea: ["sea"],
  second: ["sec", "ond"],
  secretary: ["sec", "re", "tar", "y"],
  see: ["see"],
  separate: ["sep", "a", "rate"],
  settlement: ["set", "tle", "ment"],
  she: ["she"],
  should: ["should"],
  shoulder: ["shoul", "der"],
  side: ["side"],
  signature: ["sig", "na", "ture"],
  since: ["since"],
  sincerely: ["sin", "cere", "ly"],
  sister: ["sis", "ter"],
  sleep: ["sleep"],
  slowly: ["slow", "ly"],
  small: ["small"],
  so: ["so"],
  solid: ["sol", "id"],
  some: ["some"],
  sombre: ["som", "bre"],
  someone: ["some", "one"],
  something: ["some", "thing"],
  sometimes: ["some", "times"],
  soon: ["soon"],
  specialise: ["spe", "cial", "ise"],
  spring: ["spring"],
  started: ["start", "ed"],
  statement: ["state", "ment"],
  station: ["sta", "tion"],
  stay: ["stay"],
  still: ["still"],
  stop: ["stop"],
  stopped: ["stopped"],
  straight: ["straight"],
  strength: ["strength"],
  suddenly: ["sud", "den", "ly"],
  sufficient: ["suf", "fi", "cient"],
  summer: ["sum", "mer"],
  supervise: ["su", "per", "vise"],
  sure: ["sure"],
  surprise: ["sur", "prise"],
  swimming: ["swim", "ming"],

  // ── T ──────────────────────────────────────────────────────────────
  take: ["take"],
  tamariki: ["ta", "ma", "ri", "ki"],
  taniwha: ["ta", "ni", "wha"],
  taonga: ["tao", "nga"],
  tea: ["tea"],
  tell: ["tell"],
  temperature: ["tem", "per", "a", "ture"],
  ten: ["ten"],
  than: ["than"],
  thankful: ["thank", "ful"],
  that: ["that"],
  the: ["the"],
  theatre: ["the", "a", "tre"],
  their: ["their"],
  them: ["them"],
  then: ["then"],
  there: ["there"],
  they: ["they"],
  "they're": ["they're"],
  thing: ["thing"],
  think: ["think"],
  this: ["this"],
  thorough: ["thor", "ough"],
  thought: ["thought"],
  three: ["three"],
  threw: ["threw"],
  through: ["through"],
  tikanga: ["ti", "ka", "nga"],
  time: ["time"],
  tired: ["tired"],
  to: ["to"],
  today: ["to", "day"],
  told: ["told"],
  tomorrow: ["to", "mor", "row"],
  too: ["too"],
  took: ["took"],
  top: ["top"],
  totara: ["to", "ta", "ra"],
  tradition: ["tra", "di", "tion"],
  travelled: ["trav", "elled"],
  travelling: ["trav", "el", "ling"],
  treaty: ["trea", "ty"],
  tree: ["tree"],
  triangle: ["tri", "an", "gle"],
  tried: ["tried"],
  tsunami: ["tsu", "na", "mi"],
  tuatara: ["tu", "a", "ta", "ra"],
  tui: ["tu", "i"],
  turangawaewae: ["tu", "ra", "nga", "wae", "wae"],
  turned: ["turned"],
  tussock: ["tus", "sock"],
  two: ["two"],

  // ── U ──────────────────────────────────────────────────────────────
  under: ["un", "der"],
  unhappy: ["un", "hap", "py"],
  unkind: ["un", "kind"],
  unlucky: ["un", "luck", "y"],
  unsafe: ["un", "safe"],
  untidy: ["un", "ti", "dy"],
  until: ["un", "til"],
  unusual: ["un", "u", "su", "al"],
  up: ["up"],
  us: ["us"],
  usually: ["u", "su", "al", "ly"],

  // ── V ──────────────────────────────────────────────────────────────
  vapour: ["va", "pour"],
  vegetable: ["veg", "ta", "ble"],
  vehicle: ["ve", "hi", "cle"],
  very: ["ver", "y"],
  vigour: ["vig", "our"],
  volcano: ["vol", "ca", "no"],

  // ── W ──────────────────────────────────────────────────────────────
  waiata: ["wai", "a", "ta"],
  wairua: ["wai", "ru", "a"],
  wait: ["wait"],
  waka: ["wa", "ka"],
  walk: ["walk"],
  walked: ["walked"],
  want: ["want"],
  wanted: ["want", "ed"],
  was: ["was"],
  "wasn't": ["was", "n't"],
  watch: ["watch"],
  water: ["wa", "ter"],
  way: ["way"],
  we: ["we"],
  weather: ["weath", "er"],
  weekend: ["week", "end"],
  weight: ["weight"],
  well: ["well"],
  went: ["went"],
  were: ["were"],
  "weren't": ["weren't"],
  weta: ["we", "ta"],
  what: ["what"],
  whakatauki: ["wha", "ka", "tau", "ki"],
  whakapapa: ["wha", "ka", "pa", "pa"],
  whale: ["whale"],
  whanau: ["wha", "nau"],
  when: ["when"],
  whenua: ["whe", "nu", "a"],
  where: ["where"],
  which: ["which"],
  while: ["while"],
  who: ["who"],
  why: ["why"],
  will: ["will"],
  window: ["win", "dow"],
  with: ["with"],
  woke: ["woke"],
  won: ["won"],
  work: ["work"],
  world: ["world"],
  would: ["would"],
  writing: ["writ", "ing"],

  // ── X/Y/Z ─────────────────────────────────────────────────────────
  yacht: ["yacht"],
  year: ["year"],
  yes: ["yes"],
  yesterday: ["yes", "ter", "day"],
  you: ["you"],
  your: ["your"],
};
